controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

action-logout:
    path: /logout

rutas_por_localidad_nombre:
    path: /rutas-por-localidad-nombre/{nombre}
    controller: App\Controller\RutasPorLocalidadController::mostrarRutasPorLocalidadNombre
    methods: [GET]

procesar_reserva:
    path: '/procesar_reserva'
    controller: App\Controller\ProcesarReservaController::procesarReserva'
    methods: ['POST']

guardar_valoracion:
    path: '/guardar-valoracion/{Reserva_id}'
    controller: 'App\Controller\ValoracionController::guardarValoracion'
    methods: ['POST']

ruta_editar:
    path: /ruta/editar/{id}
    controller: 'App\Controller\Api\ApiRuta::editarRuta'
    methods: ['GET']  # Método HTTP permitido para esta ruta
